version: "3.7"
services:
  frontend:
    image: "ghcr.io/safaie/frontend:latest"
    ports:
    - "8080:8080"
    environment:
    - BACKEND_DNS=backend
  backend:
    image: "ghcr.io/safaie/backend:latest"
    ports:
    - "9000:9000"
