apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie-backend
  labels:
    app: cookie-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookie-backend
  template:
    metadata:
      labels:
        app: cookie-backend
    spec:
      nodeSelector:
        agentpool: linux
      containers:
      - name: cookie-backend
        env:
          - name: REDIS_DNS
            value: cookie-redis
        image: ghcr.io/safaie/backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
          name: cookie-backend
          protocol: TCP

