apiVersion: v1
kind: Service
metadata:
  name: fortune-backend
  labels:
    app: fortune-backend
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: fortune-backend

