apiVersion: v1
kind: Service
metadata:
  name: fortune-backend
  labels:
    name: fortune-backend
spec:
  selector:
    name: fortune-backend
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
