apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-backend
  labels:
    name: fortune-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortune-backend
  template:
    metadata:
      labels:
        name: fortune-backend
    spec:
      nodeSelector:
        agentpool: linux
      containers:
        - name: fortune-backend
          image: ghcr.io/safaie/backend:latest
          ports:
            - containerPort: 9000
              name: fortune-backend
              protocol: TCP
          env:
            - name: REDIS_DNS
              value: redis
