apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      nodeSelector:
        agentpool: linux
      containers:
        - image: ghcr.io/safaie/backend:latest
          name: backend
          ports:
            - containerPort: 9000
          env:
            - name: REDIS_DNS
              value: redis
