apiVersion: v1
kind: Service
metadata:
  name: fortune-frontend
  labels:
    app: fortune-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: fortune-frontend

