apiVersion: v1
kind: Service
metadata:
  name: cookie-frontend
  labels:
    app: cookie-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: cookie-frontend

