apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
#      nodeSelector:
#        agentpool: linux
      containers:
      - name: frontend
        image: ghcr.io/safaie/frontend:latest
        ports:
          - containerPort: 8080
        env:
          - name: BACKEND_DNS
            value: backend-service
        resources: {}
      restartPolicy: Always
status: {}
