apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfc-frontend
  labels:
    app: sfc-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sfc-frontend
  template:
    metadata:
      labels:
        app: sfc-frontend
    spec:
      nodeSelector:
        agentpool: linux
      containers:
      - name: sfc-frontend
        env:
          - name: BACKEND_DNS
            valueFrom:
              configMapKeyRef:
                name: simple-fortune-config
                key: backend.dns
        image: ghcr.io/safaie/frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: sfc-frontend
          protocol: TCP

