apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie-frontend
  labels:
    app: cookie-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookie-frontend
  template:
    metadata:
      labels:
        app: cookie-frontend
    spec:
      nodeSelector:
        agentpool: linux
      containers:
      - name: cookie-frontend
        env:
          - name: BACKEND_DNS
            value: cookie-backend
        image: ghcr.io/safaie/frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: cookie-frontend
          protocol: TCP

