#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    kompose.cmd: kompose convert -f compose.yml
#    kompose.version: 1.26.1 (a9d05d509)
#  creationTimestamp: null
#  labels:
#    io.kompose.service: frontend
#  name: frontend-service
#spec:
#  type: LoadBalancer
#  ports:
#    - name: "8080"
#      port: 8080
#      targetPort: 8080
#  selector:
#    io.kompose.service: frontend
#status:
#  loadBalancer: {}


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

