apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      nodeSelector:
        agentpool: linux
      containers:
        - name: frontend
          image: ghcr.io/safaie/frontend:latest
          ports:
            - containerPort: 8080
              name: frontend
              protocol: TCP
          env:
            - name: BACKEND_DNS
              value: backend
