apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      nodeSelector:
        agentpool: linux
      containers:
      - name: redis
        image: docker.io/redis:6.0.5
        ports:
        - containerPort: 6379

