name: Continuous Delivery -- Kubernetes

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: backend
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: academy-app

jobs:

  Deploy-to-Azure:

    if: contains(github.event.pull_request.labels.*.name, 'kubernetes')

    runs-on: ubuntu-latest
    name: Deploy app container to Azure
      
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4
        with:
          namespace: # optional
          manifests: 
          images: |
            ghcr.io/safaie/backend:latest
            ghcr.io/safaie/frontend:latest
          imagepullsecrets: # optional
          # Deployment strategy to be used. Allowed values are basic, canary and blue-green
          strategy: # default is basic
          # Route based on service, ingress or SMI for blue-green strategy
          route-method: # optional, default is service
          # Indicates the buffer time in minutes before the switch is made to the green version (max is 300 min ie. 5hrs)
          version-switch-buffer: # optional, default is 0
          # Baseline and canary replicas count. Valid value between 0 to 100 (inclusive)
          baseline-and-canary-replicas: # optional, default is 0
          # Percentage of traffic redirect to canary deployment
          percentage: # optional, default is 0
          # deploy, promote, or reject
          action: # default is deploy
          # Deploy when a previous deployment already exists. If true then --force argument is added to the apply command
          force: true
          # Github token
          token: # default is ${{ github.token }}

      - name: Azure logout
        run: |
          az logout

