name: Continuous Delivery

on: 
  pull_request:
    types: [labeled]

env:
  BACKEND_IMAGE_NAME: backend
  FRONTEND_IMAGE_NAME: frontend
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: devops-academy-app

jobs:

  Deploy-to-Azure:

    if: contains(github.event.pull_request.labels.*.name, 'deploy staging')

    runs-on: ubuntu-latest
    name: Deploy app container to Azure
      
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: |
            ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.BACKEND_IMAGE_NAME}}:latest
            ${{env.IMAGE_REGISTRY_URL}}/${{ github.repository }}/${{env.FRONTEND_IMAGE_NAME}}:latest

      - name: Azure logout
        run: |
          az logout

