name: Go

on:
  push:
    branches: [ "features/*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build Backend
      run: |
        cd backend
        go mod download github.com/gomodule/redigo
        go build -v

    - name: Build Frontend
      run: |
        cd frontend
        go build -v
    
    - name: Test
      run: |
        cd frontend
        go test -v
        
    - name: Upload Backend Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: backend
        path: backend/
        if-no-files-found: error
        retention-days: 1
    
    - name: Upload Frontend Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: frontend
        path: frontend/
        if-no-files-found: error
        retention-days: 1
    
  deploy:
    needs: build
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    environment: 
      name: fortune-cookie
      url: http://http://34.241.166.1:8080
    
    steps:
    - uses: actions/checkout@v3

    - name: Download Artifacts
      uses: actions/download-artifact@v3.0.0

    - name: running application
      run: ./app.sh

